// priority: 18

ServerEvents.tags('item', event => {
    event.add('c:foods/vegetable', 'peruviandelight:aji_amarillo');
    event.add('c:foods/vegetable', 'peruviandelight:camote');
    event.add('c:foods/vegetable', 'peruviandelight:yuca');
    event.add('c:foods/vegetable', 'peruviandelight:palta_cortada');
    /*
    event.add('kubejs:malum_compatible', 'minestuck:spines_of_fluthlu')
    event.add('kubejs:malum_compatible/scythe', 'minestuck:claw_of_nrubyiglith')
    event.add('kubejs:malum_compatible', 'minestuck:thorn_of_oglogoth')
    event.add('kubejs:malum_compatible', 'minestuck:cruel_fate_crucible')
    event.add('kubejs:malum_compatible', 'minestuck:demonbane_ragripper')
    event.add('kubejs:malum_compatible', 'minestuck:hymn_for_horrorterrors')
    event.add('kubejs:malum_compatible', 'minestuck:wind_waker')
    event.add('kubejs:malum_compatible', 'minestuck:tears_of_the_enderlich_drawn')
    event.add('kubejs:malum_compatible', 'minestuck:lion_lacerators_drawn')
    event.add('kubejs:malum_compatible', 'minestuck:blue_beams')
    event.add('kubejs:malum_compatible', 'minestuck:inner_heart')
    event.add('kubejs:malum_compatible', 'minestuck:princess_peril')
    event.add('kubejs:malum_compatible', 'minestuck:basilisk_breath_dragonslayer')
    event.add('kubejs:malum_compatible/scythe', 'minestuck:kissy_cutie_heart_splitter')
    event.add('kubejs:malum_compatible/scythe', 'minestuck:mutant_cutie_cell_cutter')
    event.add('kubejs:malum_compatible/scythe', 'minestuck:time_flayer')
    event.add('kubejs:malum_compatible/scythe', 'minestuck:destiny_decimator')
    event.add('kubejs:malum_compatible/scythe', 'minestuck:green_sun_rayreaper')
    event.add('kubejs:malum_compatible/scythe', 'minestuck:hellbringers_hoe_active')
    event.add('kubejs:malum_compatible', 'minestuck:clown_club')
    event.add('kubejs:malum_compatible', 'minestuck:carnie_club')
    event.add('kubejs:malum_compatible', 'minestuck:red_eyes')
    event.add('kubejs:malum_compatible', 'minestuck:typhonic_trivializer')
    event.add('kubejs:malum_compatible', 'minestuck:prime_staff')
    event.add('kubejs:malum_compatible', 'minestuck:gothy_axe')
    event.add('kubejs:malum_compatible', 'minestuck:dragon_lance')
    event.add('kubejs:malum_compatible', 'minestuck:dragon_key')
    event.add('kubejs:malum_compatible', 'minestuck:dragon_cane_unsheathed')
    event.add('kubejs:malum_compatible', 'minestuck:chancewyrms_extra_fortunate_stabbing_implement_unsheathed')
    event.add('kubejs:malum_compatible', 'minestuck:prime_staff')
    event.add('kubejs:malum_compatible', 'minestuck:white_kings_scepter')
    event.add('kubejs:malum_compatible', 'minestuck:black_kings_scepter')
    event.add('kubejs:malum_compatible/scythe', 'e2s2:devilsknife')
    event.add('kubejs:malum_compatible', 'e2s2:black_sword')
    event.add('kubejs:malum_compatible/scythe', 'irons_spellbooks:hellrazor')
    event.add('kubejs:malum_compatible', 'irons_spellbooks:legionnaire_flamberge')
    event.add('kubejs:malum_compatible', 'alchemyexpanded:dragon_saw')
    event.add('kubejs:malum_compatible', 'alchemyexpanded:english_executioner')
    event.add('kubejs:malum_compatible', '#kubejs:malum_compatible/scythe')
    event.add('c:tools/knife', 'e2s2:red_knife')
    event.add('c:tools/knife', 'e2s2:obsidian_dagger')
    event.add('occultism:tools/knife', '#c:tools/knife')
    event.add('farmersdelight:enchantable/knife', '#c:tools/knife')
    event.add('malum:enchantable/spirit_spoils', '#kubejs:malum_compatible')
    event.add('malum:enchantable/animated', '#kubejs:malum_compatible')
    event.add('malum:enchantable/haunted', '#kubejs:malum_compatible')
    event.add('malum:enchantable/ascension', '#kubejs:malum_compatible/scythe')
    event.add('c:tools/scythe', '#kubejs:malum_compatible/scythe')
    event.add('malum:scythe', '#kubejs:malum_compatible/scythe')
    event.add('kubejs:cueball_weapons', 'minestuck:caledfwlch')
    event.add('kubejs:cueball_weapons', 'minestuck:mwrthwl')
    event.add('kubejs:cueball_weapons', 'minestuck:allweddol')
    event.add('kubejs:cueball_weapons', 'alchemyexpanded:white_magnum')
    event.add('kubejs:cueball_weapons', 'alchemyexpanded:maneg')
    event.add('kubejs:cueball_weapons', 'alchemyexpanded:olwyn_llinynnol')
    event.add('kubejs:cueball_weapons', 'alchemyexpanded:white_wand')
    event.add('kubejs:cueball_weapons', 'minestuck:genesis_godstabber')
    event.add('kubejs:cueball_weapons', 'minestuck:quill_of_echidna')
    event.add('kubejs:zilly_weapons', 'minestuck:zillyhoo_hammer')
    event.add('kubejs:zilly_weapons', 'minestuck:scarlet_zillyhoo')
    event.add('kubejs:zilly_weapons', 'minestuck:cutlass_of_zillywair')
    event.add('kubejs:zilly_weapons', 'minestuck:thistle_of_zillywich')
    event.add('kubejs:zilly_weapons', 'minestuck:popamatic_vrillyhoo')
    event.add('kubejs:zilly_weapons', 'alchemyexpanded:flintlock_of_zillyhau')
    event.add('kubejs:zilly_weapons', 'alchemyexpanded:blunderbuss_of_zillywigh')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:cooking_with_sadako')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:dragon_saw')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:carved_wand')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:resin_wand')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:break_augur')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:anvil_aurawand')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:ghost_in_the_machine')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:tildeath_do_us_part')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:bell_bat')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:dead_ringer')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:key')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:deuling_blade')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:frontier_axe')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:ashen_chainsaw')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:black_scepter')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:gold_scepter')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:green_sun_cuestaff')
    event.add('kubejs:ae_weapons/melee', 'alchemyexpanded:white_wand')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:yoyo')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:rose_rotator')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:rollup_rotator')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:cerulean_stacks')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:wizard_spinner')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:firescale_thrower')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:carbon_oracle')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:regiyoyo')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:deaths_counterweight')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:rotational_genesis')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:spinner_of_the_cycle')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:green_sun_sleeper')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:sun_rises')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:black_dragon_death_whirler')
    event.add('kubejs:ae_weapons/yoyo', 'alchemyexpanded:olwyn_llinynnol')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:boxing_glove')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:knuckle_duster')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:regiknuckle')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:royal_knuckle')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:gauntlet')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:nighttime_knockout')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:midnight_bruiser')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:fortunes_hand')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:bombing_glove')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:cobalt_crystal_pulverizer')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:meltdown_mitt')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:crystal_clawed_dragon_grip')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:lightest_touch')
    event.add('kubejs:ae_weapons/fist', 'alchemyexpanded:maneg')
    event.add('kubejs:ae_weapons', '#kubejs:ae_weapons/fist')
    event.add('kubejs:ae_weapons', '#kubejs:ae_weapons/melee')
    event.add('kubejs:ae_weapons', '#kubejs:ae_weapons/yoyo')
    event.add('minecraft:enchantable/durability', '#kubejs:ae_weapons')
    event.add('minecraft:enchantable/sharp_weapon', 'alchemy_expanded:gunblade')
    event.add('minecraft:enchantable/sharp_weapon', '#kubejs:ae_weapons/fist')
    event.add('minecraft:enchantable/sharp_weapon', '#kubejs:ae_weapons/melee')
    event.add('minecraft:enchantable/fire_aspect', '#kubejs:ae_weapons/fist')
    event.add('minecraft:enchantable/fire_aspect', '#kubejs:ae_weapons/melee')
    event.add('c:tools/melee_weapon', '#kubejs:ae_weapons/fist')
    event.add('c:tools/melee_weapon', '#kubejs:ae_weapons/melee')
    event.add('c:tools', '#kubejs:ae_weapons')
    event.add('c:spoons', 'minestuck:wooden_spoon')
    event.add('c:spoons', 'minestuck:silver_spoon')
    event.add('c:spoons', 'minestuck:nosferatu_spoon')
    event.add('c:spoons', 'minestuck:crocker_spoon')
    event.add('c:spoons', 'minestuck:golden_spork')
    event.add('c:spoons', 'minestuck:spork')
    event.add('c:spoons', 'minestuck:wooden_spoon')
    event.add('c:spoons', 'alchemyexpanded:cooking_with_sadako')
    event.add('c:spoons', 'minestuck_extended:bit_muncher')
    event.add('c:spoons', 'minestuck:throngler')
    event.add('farmersdelight:tools/knives', '#c:tools/knife')
    event.add('e2s2:bedrock_breaking_pickaxes', 'sillyworks:bedrock_pickaxe')
    event.add('e2s2:bedrock_breaking_pickaxes', 'cataclysm:void_forge')
    event.add('e2s2:bedrock_breaking_pickaxes', 'cataclysm:infernal_forge')
    event.add('e2s2:bedrock_breaking_pickaxes', 'minestuck:zillyhoo_hammer')
    event.add('e2s2:bedrock_breaking_pickaxes', 'minestuck:mwrthwl')
    event.add('e2s2:bedrock_breaking_pickaxes', 'minestuck:fear_no_anvil')
    */
    event.add('curios:ring', 'minestuck:black_queens_ring')
    event.add('curios:ring', 'minestuck:white_queens_ring')

    //newDataFullPath(event, 'c:tags/item/tea_ingredients', newTag(false, ['nomansland:thistle']));
})

ServerEvents.tags('entity_type', event => {
    // 3, like witch
    event.add('custom:tiny_exp_enemy', 'cataclysm:drowned_host', 'cataclysm:endermaptera', 'cataclysm:the_watcher');

    //5
    event.add('custom:small_exp_enemy', 'cataclysm:draugr', 'cataclysm:royal_draugr', 'cataclysm:cindaria',
        'cataclysm:deepling', 'cataclysm:deepling_angler', 'cataclysm:koboleton',
        'irons_spellbooks:cultist', 'irons_spellbooks:necromancer');

    // 10, like ravager
    event.add('custom:medium_exp_enemy', 'cataclysm:elite_draugr', 'cataclysm:coral_golem', 'cataclysm:hippocamtus',
        'cataclysm:deepling_brute', 'cataclysm:deepling_priest', 'cataclysm:deepling_warlock', 'cataclysm:ignited_berserker',
        'cataclysm:ignited_revenant', 'irons_spellbooks:citadel_keeper', 'irons_spellbooks:cryomancer', 'irons_spellbooks:pyromancer',
        'irons_spellbooks:archevoker', 'immersiveengineering:commando', 'immersiveengineering:fusilier');

    // 75
    event.add('custom:large_exp_enemy', 'cataclysm:amethyst_crab', 'cataclysm:aptrgangr', 'cataclysm:coralssus',
        'cataclysm:kobolediator', 'cataclysm:wadjet', 'cataclysm:the_prowler');

    // 125
    event.add('custom:huge_exp_enemy', 'cataclysm:clawdian');

    // These bosses spawn together in twilight final castle in Skaia. Structures are left behind in dimensions and have trial spawners with fun stuff
    //event.add('cataclysm:team_ignis', 'cataclysm:maledictus')
    //newDataFullPath(event, 'cataclysm:tags/entity_type/team_maledictus', newTag(false, ['cataclysm:ignis']));
})

//viksy
/*ServerEvents.tags('item', event => {
  event.add('c:storage_blocks/raw_uranium', 'minestuck:uranium_block')
  event.add('c:raw_materials/uranium', 'minestuck:raw_uranium')
  event.add('c:chunks/uranium', 'mekanism:raw_uranium')
  event.add('c:sausage/cooked', 'mynethersdelight:roasted_sausage')
  event.add('c:sausage/cooked', 'ends_delight:ender_sausage')
  event.add('c:sausage/raw', 'mynethersdelight:hoglin_sausage')
  event.add('c:sausage/raw', 'ends_delight:raw_ender_sausage')
  event.add('c:sausage', 'mynethersdelight:roasted_sausage')
  event.add('c:sausage', 'ends_delight:ender_sausage')
  event.add('c:sausage', 'mynethersdelight:hoglin_sausage')
  event.add('c:sausage', 'ends_delight:raw_ender_sausage')
  event.add('c:fat', 'hexerei:animal_fat')
  event.add('c:tallow', 'hexerei:animal_fat')
  event.add('c:ash', 'netherex:ash')
  event.add('c:nuggets/netherite', 'netherex:netherite_nugget')
  event.add('hexerei:tallow_meltable', 'occultism:tallow')
  event.add('c:meat/ribs/raw', 'netherex:ribs')
  event.add('c:mutton/ribs', 'netherex:ribs')
  event.add('c:chocolate/bar', 'create:bar_of_chocolate')
  event.add('c:chocolate/milk/bar', 'create:bar_of_chocolate')
  event.add('c:candy', '#minestuck:grist_candy')
  event.add('c:candy', 'minestuck:candy_corn')
  event.add('c:bread/crumbs', 'minestuck:breadcrumbs')
  event.add('c:candy', 'supplementaries:candy')
  event.add('c:foods/onion', 'minestuck:onion')
  event.add('c:crops/onion', 'minestuck:onion')
  event.add('c:fruits', 'minestuck:desert_fruit')
  event.add('c:foods/fruit', 'minestuck:desert_fruit')
  event.add('c:fruit', 'minestuck:desert_fruit')
  event.add('c:fruits', 'nomansland:pear')
  event.add('c:foods/fruit', 'nomansland:pear')
  event.add('c:fruit', 'nomansland:pear')
  event.add('c:fruits', 'minestuck:strawberry_chunk')
  event.add('c:foods/fruit', 'minestuck:strawberry_chunk')
  event.add('c:fruit', 'minestuck:strawberry_chunk')
  event.add('c:foods/berry', 'alchemyexpanded:wizard_berries')
  event.add('c:fruit', 'alchemyexpanded:wizard_berries')
  event.add('c:fruits', 'alchemyexpanded:wizard_berries')
  event.add('c:chicken/breast/raw', 'farmersdelight:chicken_cuts')
  event.add('c:chicken/cubed/raw', 'farmersdelight:chicken_cuts')
  event.add('c:chicken/thigh/raw', 'farmersdelight:chicken_cuts')
  event.add('c:beef/cubed/raw', 'farmersdelight:minced_beef')
  event.add('c:pork/ground/raw', 'farmersdelight:minced_beef')
  event.add('mynethersdelight:hot_spice', 'extradelight:hot_sauce_item')
  event.add('c:bricks/nether', 'netherex:fiery_nether_brick')
  event.add('c:bricks/nether', 'netherex:gloomy_nether_brick')
  event.add('c:bricks/nether', 'netherex:lively_nether_brick')
  event.add('supplementaries:throwable_bricks', 'netherex:fiery_nether_brick')
  event.add('supplementaries:throwable_bricks', 'netherex:gloomy_nether_brick')
  event.add('supplementaries:throwable_bricks', 'netherex:lively_nether_brick')
  event.add('c:bricks', 'supplementaries:ash_brick')
  event.add('c:crushed_aluminum', 'create:crushed_raw_aluminum')
  event.add('c:beef/ground', 'farmersdelight:minced_beef')
  event.add('c:foods/milk', 'hexerei:milk_bottle')
  event.add('c:foods/milk', 'extradelight:soy_milk')
  event.add('c:ores/stellarite', 'e2s2:asterite_ore')
  event.add('c:ores/nebulite', 'enderscape:nebulite_ore')
  event.add('c:ores/shadoline', 'enderscape:shadoline_ore')
  event.add('c:ores/iridium', 'malum:cthonic_gold_ore')
  event.add('c:ores/soulstone', 'malum:soulstone_ore')
  event.add('c:ores/blazing_quartz', 'malum:blazing_quartz_ore')
  event.add('c:ingots/black_steel', 'cataclysm:black_steel_ingot')
  event.add('irons_spellbooks:blood_focus', 'hexerei:blood_bottle')
  event.add('c:raw_materials/soulstone', 'malum:raw_soulstone')
  event.add('malum:crushed_soulstone', 'malum:crushed_soulstone')
  event.add('c:raw_materials/brilliance', 'malum:raw_brilliance')
  event.add('malum:crushed_brilliance', 'malum:crushed_brilliance')
  event.add('kubejs:ink_base', 'minecraft:ink_sac')
  event.add('kubejs:ink_base', 'minecraft:glow_ink_sac')
  event.add('kubejs:ink_base', 'minestuck:ink_squid_pro_quo')
  event.add('kubejs:ink_base', 'supplementaries:antique_ink')
  event.add('kubejs:taboo_books', 'minestuck:grimoire')
  event.add('kubejs:godspec', 'e2s2:godsoul_ingot')
  event.add('kubejs:godspec', 'e2s2:godspec_helmet')
  event.add('kubejs:godspec', 'e2s2:godspec_chestplate')
  event.add('kubejs:godspec', 'e2s2:godspec_leggings')
  event.add('kubejs:godspec', 'e2s2:godspec_boots')
  event.add('sillyworks:power_armor', 'e2s2:godspec_helmet')
  event.add('sillyworks:power_armor', 'e2s2:godspec_chestplate')
  event.add('sillyworks:power_armor', 'e2s2:godspec_leggings')
  event.add('sillyworks:power_armor', 'e2s2:godspec_boots')
  event.add('sillyworks:prevents_power_armor_setbonus', 'e2s2:godspec_helmet')
  event.add('sillyworks:prevents_power_armor_setbonus', 'e2s2:godspec_chestplate')
  event.add('sillyworks:prevents_power_armor_setbonus', 'e2s2:godspec_leggings')
  event.add('sillyworks:prevents_power_armor_setbonus', 'e2s2:godspec_boots')
  event.add('sillyworks:power_armor', 'minestuck:iron_lass_glasses')
  event.add('sillyworks:power_armor', 'minestuck:iron_lass_chestplate')
  event.add('sillyworks:power_armor', 'minestuck:iron_lass_skirt')
  event.add('sillyworks:power_armor', 'minestuck:iron_lass_shoes')
  event.add('sillyworks:prevents_power_armor_setbonus', 'minestuck:iron_lass_glasses')
  event.add('sillyworks:prevents_power_armor_setbonus', 'minestuck:iron_lass_chestplate')
  event.add('sillyworks:prevents_power_armor_setbonus', 'minestuck:iron_lass_skirt')
  event.add('sillyworks:prevents_power_armor_setbonus', 'minestuck:iron_lass_shoes')
  event.add('kubejs:godspec', 'e2s2:unfinished_godspec_helmet')
  event.add('kubejs:godspec', 'e2s2:unfinished_godspec_chestplate')
  event.add('kubejs:godspec', 'e2s2:unfinished_godspec_leggings')
  event.add('kubejs:godspec', 'e2s2:unfinished_godspec_boots')
  event.add('kubejs:wizardberries', 'alchemyexpanded:wizard_berries')
  event.add('kubejs:wizardberries', 'alchemyexpanded:wizardberry_gushers')
  event.add('e2s2:void_guard', 'e2s2:godspec_chestplate')
  event.add('mekanism:alloys/infused', 'sillyworks:superconductor_ingot')
  event.add('c:alloys/advanced', 'sillyworks:superconductor_ingot')
  event.add('c:bones/wither', 'netherex:wither_bone')
  event.add('c:mushrooms', 'netherex:red_elder_mushroom')
  event.add('c:mushrooms', 'netherex:brown_elder_mushroom')
  event.add('c:mushrooms', 'minestuck:morel_mushroom')
  event.add('c:mushrooms', 'minestuck:glowing_mushroom')
  event.add('c:mushrooms', 'minestuck:paradises_portabello')
  event.add('c:mushrooms', 'nomansland:shelf_mushroom')
  event.add('c:mushrooms', 'nomansland:grilled_mushrooms')
  event.add('c:mushrooms', 'minestuck:sushroom')
  event.add('c:mushrooms', 'enderscape:celestial_chanterelle')
  event.add('c:mushrooms', 'enderscape:murublight_chanterelle')
  event.add('c:mushrooms', 'enderscape:murublight_shelf')
  event.add('nomansland:edible_mushrooms', 'minestuck:morel_mushroom')
  event.add('c:foods/dough', 'create:dough')
  event.add('c:doughs', 'farmersdelight:wheat_dough')
  event.add('c:doughs/wheat', 'farmersdelight:wheat_dough')
  event.add('c:beef/roast', 'minecraft:beef')
  event.add('c:liver', 'minecraft:beef')
  event.add('c:bread/sliced', 'mynethersdelight:slices_of_bread')
  event.add('c:toast', 'mynethersdelight:toasts')
  event.add('kubejs:strange_crystals', 'malum:strange_crystal')
  event.add('kubejs:strange_crystals', 'malum:large_strange_crystal')
  event.add('minestuck:unreadable', '#c:ingots/uranium')
  event.add('sillyworks:power_armor_wiring', 'createaddition:electrum_spool')
  event.add('minecraft:coals', 'tfmg:coal_coke')
  event.add('ae2:all_quartz_dust', 'mekanism:dust_quartz')
  event.add('c:tools/shield', 'endermanoverhaul:corrupted_shield')
  event.add('minecraft:enchantable/durability', 'endermanoverhaul:corrupted_shield')
  event.add('kubejs:french_fries', 'extradelight:french_fries')
  event.add('kubejs:french_fries', 'minestuck:french_fry')
  event.add('c:condiments', 'minestuck:grub_sauce')
  event.add('neoforge:dusts/obsidian', '#c:dusts/obsidian')
  event.add('neoforge:dusts/gold', '#c:dusts/gold')
  event.add('c:foods/cookie', 'minestuck_extended:lancer_cookie')
  event.add('c:slag', 'tfmg:slag')
  event.add('immersiveengineering:treated_wood', 'minestuck:treated_planks')
  event.add('immersiveengineering:treated_wood', 'minestuck:treated_heavy_planks')
  event.add('immersiveengineering:treated_wood', 'minestuck:treated_uncarved_wood')
  event.add('immersiveengineering:treated_wood', 'tfmg:hardened_planks')
  event.add('immersiveengineering:treated_wood_slab', 'minestuck:treated_planks_slab')
  event.add('immersiveengineering:treated_wood_slab', 'minestuck:treated_heavy_plank_slab')
  event.add('immersiveengineering:treated_wood_slab', 'minestuck:treated_uncarved_wood_slab')
  event.add('minestuck:unreadable', 'season_x:cueball_round')
  event.add('minestuck:unreadable', '#c:ingots/plastic')
  event.add('minestuck:unreadable', '#c:ingots/silicon')
  event.add('minestuck:unreadable', '#c:ingots/superconductor')
  event.add('minestuck:unreadable', '#c:ingots/steel')
  event.add('minestuck:unreadable', '#c:ingots/iesnium')
  event.add('minestuck:unreadable', 'tfmg:steel_mechanism')
  event.add('minestuck:unreadable', 'tfmg:circuit_board')
  event.add('minestuck:unreadable', 'malum:soul_stained_steel_ingot')
  event.add('minestuck:unreadable', 'malum:hallowed_gold_ingot')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_tile')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_sheet')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_slab')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_tile_slab')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_sheet_slab')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_stairs')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_tile_stairs')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_sheet_stairs')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_wall')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_button')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_pressure_plate')
  event.add('kubejs:cast_iron_blocks', 'minestuck:cast_iron_frame')
  event.add('kubejs:cast_iron_blocks', 'minestuck:chiseled_cast_iron')
  event.add('kubejs:final_materials', 'season_x:phantasmagorium')
  event.add('kubejs:final_materials', 'sillyworks:supercomputer')
  event.add('sillyworks:superheavy', 'immersiveengineering:railgun')
  event.add('sillyworks:superheavy', 'immersiveengineering:chemthrower')
  event.add('sillyworks:superheavy', 'tfmg:flamethrower')
  event.add('sillyworks:superheavy', 'tfmg:advanced_potato_cannon')
  event.add('sillyworks:superheavy', 'tfmg:quad_potato_cannon')
  event.add('kubejs:lithium_charge', 'tfmg:lithium_charge')
  event.add('kubejs:magic_cloth', 'irons_spellbooks:magic_cloth')
  event.add('kubejs:magic_cloth', 'malum:soulwoven_silk')
  event.add('supplementaries:ropes', 'immersiveengineering:wirecoil_structure_rope')
  event.add('malum:artifice_tool', 'minestuck:tuning_fork')
  event.add('sillyworks:stone_alloys', 'create:andesite_alloy')
  event.add('hexerei:herbs', 'alchemyexpanded:wizard_berries')
  //---------------------------------------------------------------------
  event.remove('c:storage_blocks/uranium', 'minestuck:uranium_block')
  event.remove('c:ingots/silicon', 'tfmg:silicon_ingot')
  event.remove('minestuck:faygo', 'faygoplus:ultimate_faygo')
  event.remove('c:dusts/amethyst', 'occultism:amethyst_dust')
  event.remove('c:dusts/netherite_scrap', 'occultism:netherite_scrap_dust')
  event.remove('c:dusts/blackstone', 'occultism:crushed_blackstone')
  event.remove('sillyworks:power_armor_plates', '#c:plates/iron')
  event.remove('sillyworks:power_armor_wiring', 'minecraft:copper_ingot')
  event.remove('sillyworks:ae2_redstone', '#c:dusts/redstone')
})



ServerEvents.tags('block', event => {
  event.add('minecraft:enchantment_power_provider', '#minestuck:bookshelves/aspect')
  event.add('minecraft:enchantment_power_provider', '#c:bookshelves')
})


//---------------------------------------------------------------------
ServerEvents.tags('fluid', event => {
  event.add('c:blood', 'minestuck:blood')
  event.add('c:blood', 'hexerei:blood_fluid')
  event.add('c:blood', 'irons_spellbooks:blood')
  event.add('sillyworks:strong_acid', 'sillyworks:strong_acid')
})
*/