[tooltip]
	#Whether to show the shield special effects in the tooltip
	shield_info = true
	#How boondollar costs are shown when wearing an item that makes them visible
	#DISABLED: completely hides the value
	#RAW: displays lowest and highest prices (when available)
	#AVERAGE: displays the middle ground for the above
	#RANDOM: displays a random value between the lowest and highest
	#Allowed Values: DISABLED, RAW, AVERAGE, RANDOM
	boondollar_display = "RANDOM"
	#Whether to show innate enchantments if they are present
	#In case you have another mod that shows them anyways
	innate_enchantments = true
	#If enabled, infused visions will include a warning about the use limit
	vision_warning = true
	#If enabled, compat items which require a specific mod will mention it in their tooltip
	missing_mod = true

[grist_viewers]
	#Specifies the grist viewers display the current location's grist layer info
	#TOP/CENTER/BOTTOM: Where the grist is shown vertically
	#LEFT/MIDDLE/RIGHT: Where the grist is shown horizontally
	#Allowed Values: TOP_LEFT, TOP_MIDDLE, TOP_RIGHT, CENTER_LEFT, CENTER_MIDDLE, CENTER_RIGHT, BOTTOM_LEFT, BOTTOM_MIDDLE, BOTTOM_RIGHT
	location = "TOP_LEFT"
	#If enabled, the grist display will be colored with the grist's color
	colored = false
	#If enabled, the grist display will be followed with the grist's name
	name = true
	#If enabled, the grist display will be followed with the grist's texture
	grist = false

	[grist_viewers.custom_location]
		#If enabled, the grist display will be aligned based on the given coordinates instead of the screen size
		#This means that TOP_LEFT will treat the coordinates as the top left corner of the screen
		#and that BOTTOM_MIDDLE will treat the coordinates as the bottom middle of the screen
		enabled = false
		#Horizontal coordinates of the display, from the left
		# Default: 0
		# Range: > 0
		x = 0
		#Vertical coordinates of the display, from the top
		# Default: 0
		# Range: > 0
		y = 0

[compat]
	#If enabled and Create is installed, mysterious convertion recipes will be added for Extrastuck items
	convertion_recipes = true
	#If enabled and Ponder is installed, Minestuck machines will have ponder entries
	ponder_minestuck_machines = true
