#How many charges a radbow gets from an uranium rod
# Default: 10
# Range: > 1
radbow_charge = 10
#If true, the Rainbow Bow will pick effects from the "extrastuck:rainbowbow_effects" tag instead of being fully random
rainbowbow_whitelist = false

[reactor]
	#How much uranium power should a reactor hold
	#Should be higher than the amount produced per tick, otherwise reactors won't run
	# Default: 512
	# Range: > 1
	uranium_storage = 512
	#How much FE should a reactor hold
	#Should be higher than the amount produced per tick, otherwise reactors won't run
	# Default: 2560000
	# Range: > 1
	fe_storage = 2560000
	#How much fluid should a reactor hold
	#Should be higher than the amount consumed per tick, otherwise reactors won't run
	# Default: 4000
	# Range: > 1
	fluid_storage = 4000
	#How much FE is produced per tick while the reactor is working
	# Default: 5000
	# Range: > 1
	fe_tick = 5000
	#How much uranium is produced per tick while the reactor is working
	# Default: 1
	# Range: > 1
	uranium_tick = 1
	#How much fluid is consumed per tick, in mB, while the reactor is working
	# Default: 10
	# Range: > 1
	fluid_tick = 10
	#Limit to how much FE can be sent in a tick to each neighbors
	#Meaning that if all 6 neighbors can receive FE, 6 times this amount will be sent every tick
	# Default: 10000
	# Range: > 1
	max_fe_transfer = 10000
	#Limit to how much uranium power can be sent in a tick to each neighbors
	#Meaning that if all 6 neighbors can receive uranium power, 6 times this amount will be sent every tick
	# Default: 8
	# Range: 1 ~ 32767
	max_uranium_transfer = 8
	#If true, reactors explode if they have fuel but no fluid
	explode = false

[charger]
	#How much uranium power should a charger hold
	#Shouldn't be lower than 32, as that would prevent uranium chunks from being used
	# Default: 128
	# Range: 0 ~ 32767
	uranium_storage = 128
	#How much FE should a charger hold
	#Should be higher than the amount than the amount produced per tick, otherwise charger won't self-charge
	# Default: 64000
	# Range: > 1
	fe_storage = 64000
	#How much FE is produced per tick, at the cost of 1 uranium power
	# Default: 500
	# Range: > 1
	fe_tick = 500
	#How much FE is transferred between storage and item per tick
	#Mostly to make charging fancier
	# Default: 1000
	# Range: > 1
	fe_transfer = 1000

[blaster]
	#How much uranium power should a blaster hold
	#Note that each shot consumes 1 uranium power
	#Shouldn't be lower than 32, as that would prevent uranium chunks from being used
	# Default: 128
	# Range: 1 ~ 32767
	uranium_storage = 128

[cosmic_spore]
	#Determines which dimensions trigger the Cosmic Plague Spore's inventory effect
	#This is separate from the "extrastuck:cosmic_dimension_types" tag and should only be used in case multiple dimensions use the same type
	# Default: []
	dimensions = []
	#If enabled, Cosmic Plague Spore will give Cosmic Plague II, which can spread to nearby entities
	#Otherwise, it will only give Poison V
	hard_mode = false

[cosmic_plague]
	#If true, Cosmic Plague attempts to spread to nearby entities that are not tagged "extrastuck:cosmic_plague_immune"
	#Does not prevent initial application, use the tag for that
	spread = true
	#Sets the range for Cosmic Plague's spread
	#Does not have to be an integer
	# Default: 5.0
	# Range: 0.0 ~ 2.147483647E9
	range = 5.0

	[modus.mastermind]
		#How many colors are available by default in mastermind cards
		#Existing cards will not be affected
		# Default: 3
		# Range: 1 ~ 6
		difficulty = 3
		#If true, captchalogued mastermind cards will be stored in a more difficult card when retrieved from a mastermind modus
		incremental = false
		#If true, the Mastermind Modus Card can have its default difficulty changed
		change = true
		#If true, Mastermind Codebreaker can change a Mastermind Modus Card's default difficulty
		#Only affects data components if change is disabled
		change_with_pc = true

	[modus.furnace]
		#How much fuel (in ticks) does it cost to extract an item from the Furnace Modus
		#Does not apply to items that can be smelted in a furnace (these have the cost to smelt 1)
		# Default: 200
		# Range: > 0
		default_cost = 200

	[weapons.steam_powered]
		#How much fuel (in ticks) allows refueling a steam-powered weapon
		#That is to say, if the weapon's fuel is below or equal to this number, it can be refueled
		#Note that if the value is too low, it may prevent the item from being refuelable
		# Default: 200
		# Range: > 0
		fuel_threshold = 200
		#How much fuel (in ticks) is consumed to attack with a steam-powered weapon
		# Default: 200
		# Range: > 0
		fuel_consume = 200

[vision]
	#If true, empty visions can be tuned by aspect holders to their own aspect
	tuning = true
	#If true, players with no aspect cannot tune visions into useless ones
	safe_tuning = false
	#How many visions can be active at once for a player
	#This is limited to the amount of aspects
	# Default: 1
	# Range: 0 ~ 12
	limit = 1
	#Minimum rung needed to attune a vision
	#Set to -1 for no minimum
	rung = -1

	[integration.irons_spellbooks]
		#Which amplifier of Creative Shock should prevent spell casting for non-creative players
		#Note that an amplifier of 3 means level IV
		creative_shock_survival = 1
		#Which amplifier of Creative Shock should prevent spell casting for creative players
		#Note that an amplifier of 3 means level IV
		creative_shock_creative = 4
