[interpreters]
	#If true, default create interpreters are loaded
	create = true
	#If true, default farmer's delight interpreters are loaded
	farmersdelight = true

	[integration.irons_spellbooks]
		#If true, adds grist costs to Iron's Spells & Spellbooks items
		grist_costs = true
		#If true, adds combination recipes to multiple Iron's Spells & Spellbooks items
		combinations = true
		#If true, adds combination recipes to Iron's Spells & Spellbooks items that are dropped by entities
		#These include the Rotten Spell Book, Blood Staff, and Hither-Thither Wand
		#Basically, most non-craftable Iron's Spellbooks items
		loot_combinations = false
